{
  "DATA_PATH" : "/Data/obrichta/datasets",
  "RESULTS_PATH" : "./Results",
  "SPLITS_PATH" : "./datasets/splits",
  "TESTS_PATH" : "./Tests",
  "use_wandb_tracking" : True,
  "project": "k-WL-turbo"
}